# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

cpp_string_ops <- function(Rstr, is_dsb) {
    .Call(`_stringmagick_cpp_string_ops`, Rstr, is_dsb)
}

cpp_string_ops_full_string <- function(Rstr, is_dsb) {
    .Call(`_stringmagick_cpp_string_ops_full_string`, Rstr, is_dsb)
}

cpp_string_op_if_extract_old <- function(Rstr) {
    .Call(`_stringmagick_cpp_string_op_if_extract_old`, Rstr)
}

cpp_string_op_if_extract <- function(Rstr) {
    .Call(`_stringmagick_cpp_string_op_if_extract`, Rstr)
}

cpp_paste_conditional <- function(x, id, sep = "", sep_last = "") {
    .Call(`_stringmagick_cpp_paste_conditional`, x, id, sep, sep_last)
}

cpp_extract_quote_from_op <- function(Rstr) {
    .Call(`_stringmagick_cpp_extract_quote_from_op`, Rstr)
}

cpp_parse_operator <- function(Rstr) {
    .Call(`_stringmagick_cpp_parse_operator`, Rstr)
}

cpp_normalize_ws <- function(Rstr) {
    .Call(`_stringmagick_cpp_normalize_ws`, Rstr)
}

cpp_normalize_string <- function(Rstr, clean_punct, clean_digit, clean_isolated) {
    .Call(`_stringmagick_cpp_normalize_string`, Rstr, clean_punct, clean_digit, clean_isolated)
}

cpp_trimws <- function(x) {
    .Call(`_stringmagick_cpp_trimws`, x)
}

cpp_which_empty <- function(Rstr) {
    .Call(`_stringmagick_cpp_which_empty`, Rstr)
}

cpp_find_first_index <- function(index, nb, is_last) {
    .Call(`_stringmagick_cpp_find_first_index`, index, nb, is_last)
}

cpp_group_rev_index <- function(index) {
    .Call(`_stringmagick_cpp_group_rev_index`, index)
}

cpp_recreate_index <- function(id) {
    .Call(`_stringmagick_cpp_recreate_index`, id)
}

cpp_parse_charselect <- function(Rstr) {
    .Call(`_stringmagick_cpp_parse_charselect`, Rstr)
}

cpp_parse_conditions_in_pattern <- function(Rstr) {
    .Call(`_stringmagick_cpp_parse_conditions_in_pattern`, Rstr)
}

cpp_parse_name_stars <- function(Rstr) {
    .Call(`_stringmagick_cpp_parse_name_stars`, Rstr)
}

cpp_is_trailing_dots <- function(Rstr) {
    .Call(`_stringmagick_cpp_is_trailing_dots`, Rstr)
}

cpp_is_variable_name <- function(Rstr) {
    .Call(`_stringmagick_cpp_is_variable_name`, Rstr)
}

cpp_equal_ignore_case <- function(x_Rstr, y_Rstr, ignore_case = TRUE) {
    .Call(`_stringmagick_cpp_equal_ignore_case`, x_Rstr, y_Rstr, ignore_case)
}

cpp_is_int_in_char <- function(Rstr) {
    .Call(`_stringmagick_cpp_is_int_in_char`, Rstr)
}

cpp_to_integer <- function(x) {
    .Call(`_stringmagick_cpp_to_integer`, x)
}

cpp_combine_clusters <- function(cluster_list, index) {
    .Call(`_stringmagick_cpp_combine_clusters`, cluster_list, index)
}

cpp_create_pos <- function(index) {
    .Call(`_stringmagick_cpp_create_pos`, index)
}

